const mongoose = require('mongoose')
const { dbURI } = require('../config/environment')
const Project = require('../models/project')
const User = require('../models/user')

mongoose.connect(dbURI, { useNewUrlParser: true, useUnifiedTopology: true }, (err, db) => {
  if (err) return console.log(err)
  db.dropDatabase()
    .then(() => {
      return User.create([
        {
          username: 'John',
          name: 'john',
          email: 'john@john.com',
          password: 'pass',
          passwordConfirmation: 'pass',
          bio: 'This is a bio for john and this is a test. More information to come',
          profileImage: 'https://d3fc22kf489ohb.cloudfront.net/assets/426e9538a23b570b87f8570788f91e1844658718/static/media/sell-your-stuff.4dfcab0e.jpg',
          location: 'Glasgow',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          username: 'Abigail',
          name: 'abi',
          email: 'abi@abi.com',
          password: 'pass',
          passwordConfirmation: 'pass',
          bio: 'This is a bio for abi and this is a test. More information to come',
          profileImage: 'https://pbs.twimg.com/profile_images/1209226898003378187/6NstjMiG_400x400.jpg',
          location: 'London',
          level: 'Mid-level',
          skills: { skill: 'JavaScript' }
        },
        {
          username: 'Jos',
          name: 'jos',
          email: 'jos@jos.com',
          password: 'pass',
          passwordConfirmation: 'pass',
          bio: 'This is a bio for jos and this is a test. More information to come',
          profileImage: 'https://i.pinimg.com/474x/b4/fc/cc/b4fccc8af248028ac48839626c0a7120--american-man-american-actors.jpg',
          location: 'Kent',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          username: 'Nic',
          name: 'nic',
          email: 'nic@nic.com',
          password: 'pass',
          passwordConfirmation: 'pass',
          bio: 'This is a bio for nic and this is a test. More information to come',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/08/everpress_5050_justice4Grenfell_T-shirt_fundraiser_0055_Brightness_Contrast-47.jpg',
          location: 'Northern Ireland',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Olympie',
          username: 'OlympieMaffia',
          email: 'omaffia0@oakley.com',
          password: 'XMoadxaIybFk',
          passwordConfirmation: 'XMoadxaIybFk',
          bio: 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/08/5050-3.jpg',
          location: 'Bābolsar',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Adelheid',
          username: 'AdelheidAlsop',
          email: 'aalsop1@amazon.co.uk',
          password: 'b9MIZT7fbkhe',
          passwordConfirmation: 'b9MIZT7fbkhe',
          bio: 'at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede',
          profileImage: 'https://thevinylfactory.com/wp-content/uploads/2019/08/erpress.jpg',
          location: 'Langpas',
          level: 'Mid-level',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Perle',
          username: 'PerleWaples',
          email: 'pwaples2@acquirethisname.com',
          password: 'y270uJ4',
          passwordConfirmation: 'y270uJ4',
          bio: 'tincidunt lacus at velit vivamus vel nulla eget eros elementum',
          profileImage: 'https://2.bp.blogspot.com/-DjRSRf0Ty0I/VuHi5b1ZLDI/AAAAAAAAB_M/yzBQkj1fnqwD14Dc-mlP5sfNG0cmQLRuQ/s1600/SAM_2471-2.jpg',
          location: 'Wenheng',
          level: 'Senior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Leanora',
          username: 'LeanoraHele',
          email: 'lhele3@oracle.com',
          password: 'CBXz9Zaxkj',
          passwordConfirmation: 'CBXz9Zaxkj',
          bio: 'semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis',
          profileImage: 'https://f3e6t7k9.stackpathcdn.com/wp-content/uploads/2019/09/everpress-loti.jpg',
          location: 'Jaro',
          level: 'Junior',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Sally',
          username: 'SallyBatchellor',
          email: 'sbatchellor4@shutterfly.com',
          password: 'qPQwDAvn',
          passwordConfirmation: 'qPQwDAvn',
          bio: 'felis ut at dolor quis odio consequat varius integer ac',
          profileImage: 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/34e0d970919421.5bc62ce3f2068.jpg',
          location: 'Pontian',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Serena',
          username: 'SerenaIddenden',
          email: 'siddenden5@boston.com',
          password: 'DZdmp1',
          passwordConfirmation: 'DZdmp1',
          bio: 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam',
          profileImage: 'https://pbs.twimg.com/media/EQlQbXGWoAA32vC.jpg',
          location: 'Danghara',
          level: 'Mid-level',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Adelice',
          username: 'AdeliceFranken',
          email: 'afranken6@tiny.cc',
          password: '4sPBT7PrWF',
          passwordConfirmation: '4sPBT7PrWF',
          bio: 'luctus rutrum nulla tellus in sagittis dui vel nisl duis',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2018/11/FEATURED-IMAGE.jpg',
          location: 'Dazhongzhuang',
          level: 'Mid-level',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Dori',
          username: 'DoriCattach',
          email: 'dcattach7@bravesites.com',
          password: '13vVL5',
          passwordConfirmation: '13vVL5',
          bio: 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/07/chris_black_vintage_t-shirt_collection.jpg',
          location: 'Panoongan',
          level: 'Mid-level',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Bernete',
          username: 'BerneteKleeborn',
          email: 'bkleeborn8@google.co.jp',
          password: 'aQsF66MOdgX',
          passwordConfirmation: 'aQsF66MOdgX',
          bio: 'odio condimentum id luctus nec molestie sed justo pellentesque viverra',
          profileImage: 'https://www.thedropdate.com/wp-content/uploads/2018/05/EVERPRESS-50-50-7.jpg',
          location: 'Piła',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Gladys',
          username: 'GladysWhetland',
          email: 'gwhetland9@cbsnews.com',
          password: 'dHjQR9',
          passwordConfirmation: 'dHjQR9',
          bio: 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris',
          profileImage: 'https://imgix.bustle.com/uploads/image/2018/6/1/81adf88d-4e04-4248-9e0c-3ba5f4bda470-grenfell-tower-everpress.jpg',
          location: 'Chicago',
          level: 'Junior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Joella',
          username: 'JoellaGilfoy',
          email: 'jgilfoya@psu.edu',
          password: 'w5EbSrdL',
          passwordConfirmation: 'w5EbSrdL',
          bio: 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/04/everpress_planning_your_year.jpg',
          location: 'Placencia',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Benny',
          username: 'BennyGhidetti',
          email: 'bghidettib@bbb.org',
          password: 'SmBrE0F',
          passwordConfirmation: 'SmBrE0F',
          bio: 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/04/JOY.jpg',
          location: 'Paris 02',
          level: 'Mid-level',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Hally',
          username: 'HallyPrew',
          email: 'hprewc@storify.com',
          password: 'JmY1TOCIT',
          passwordConfirmation: 'JmY1TOCIT',
          bio: 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/11/david_vujanic_everpress_t-shirts_merch_have_a_nice.jpg',
          location: 'Cavaillon',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Alanah',
          username: 'AlanahStead',
          email: 'asteadd@ucsd.edu',
          password: 'wwwy8kBGF',
          passwordConfirmation: 'wwwy8kBGF',
          bio: 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue',
          profileImage: 'https://fadmagazine.com/wp-content/uploads/rsz_bfa_29581_3946345-1024x819.jpg',
          location: 'Dallas',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Rica',
          username: 'RicaGregon',
          email: 'rgregone@pinterest.com',
          password: '0rxz0m',
          passwordConfirmation: '0rxz0m',
          bio: 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/06/KM-LM.jpg',
          location: 'Saint-Brieuc',
          level: 'Senior',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Kaile',
          username: 'KaileVoyce',
          email: 'kvoycef@reuters.com',
          password: 'RkBKnMHJ',
          passwordConfirmation: 'RkBKnMHJ',
          bio: 'ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2018/06/20180522_Amnesty5050_JoyMiessi-791x1024.jpg',
          location: 'Alcanena',
          level: 'Junior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Linnea',
          username: 'LinneaWigzell',
          email: 'lwigzellg@go.com',
          password: 'WF4tdtd',
          passwordConfirmation: 'WF4tdtd',
          bio: 'praesent id massa id nisl venenatis lacinia aenean sit amet',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/03/everpress_pre-order_t-shirt_campaign.jpg',
          location: 'Suzhou',
          level: 'Junior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Monah',
          username: 'MonahMartine',
          email: 'mmartineh@chron.com',
          password: 'kAZBOX',
          passwordConfirmation: 'kAZBOX',
          bio: 'eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/02/t-shirt-photography.jpg',
          location: 'Jejkowice',
          level: 'Mid-level',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Nicoline',
          username: 'NicolineLaxe',
          email: 'nlaxei@t.co',
          password: 'BCzSCm7',
          passwordConfirmation: 'BCzSCm7',
          bio: 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/06/KM-LM-5.jpg',
          location: 'Mayapusi',
          level: 'Junior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Eran',
          username: 'EranLamacraft',
          email: 'elamacraftj@answers.com',
          password: 'j6SS1fxmWfIX',
          passwordConfirmation: 'j6SS1fxmWfIX',
          bio: 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2017/12/lydia-yang-get-to-know-everpress.jpg',
          location: 'Ibirataia',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Ralina',
          username: 'RalinaMeechan',
          email: 'rmeechank@cornell.edu',
          password: 'jFnQky7ue',
          passwordConfirmation: 'jFnQky7ue',
          bio: 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2019/03/DSC_6185.jpg',
          location: 'Lýkeio',
          level: 'Junior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Jessie',
          username: 'JessiedeClerq',
          email: 'jdel@unicef.org',
          password: 'q8qI2fGfnO',
          passwordConfirmation: 'q8qI2fGfnO',
          bio: 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis',
          profileImage: 'https://everpress.com/blog/wp-content/uploads/2018/01/charlotte-mei-everpress.jpg',
          location: 'Bungoma',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Winny',
          username: 'WinnyKanwell',
          email: 'wkanwellm@phpbb.com',
          password: 'J1dSdEgetN',
          passwordConfirmation: 'J1dSdEgetN',
          bio: 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et',
          profileImage: 'https://dcxvepib5r3t6.cloudfront.net/attachments/file_s3s/56ce/cb09/1403/4436/482e/8541/original/qv0vx1hygc1mmi4pb39s.jpg?1460673520',
          location: 'Ladoeiro',
          level: 'Junior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Brenn',
          username: 'BrennBenn',
          email: 'bbennn@prweb.com',
          password: 'Z4MSD0g',
          passwordConfirmation: 'Z4MSD0g',
          bio: 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus',
          profileImage: 'https://blog.etsy.com/en/files/2013/01/charlotte-mei-etsy-1.jpg',
          location: 'Onueke',
          level: 'Junior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Codi',
          username: 'CodiMingasson',
          email: 'cmingassono@vistaprint.com',
          password: 'MXs0oq',
          passwordConfirmation: 'MXs0oq',
          bio: 'risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam',
          profileImage: 'https://i.pinimg.com/originals/82/8b/93/828b931c6a9059ea06fdcfb8f9c36303.png',
          location: 'Gaozhai',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Imogen',
          username: 'ImogenSykora',
          email: 'isykorap@naver.com',
          password: 'GOiBmbrztAK',
          passwordConfirmation: 'GOiBmbrztAK',
          bio: 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat',
          profileImage: 'https://data.whicdn.com/images/331376221/original.jpg',
          location: 'Stavanger',
          level: 'Mid-level',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Neely',
          username: 'NeelyFawlo',
          email: 'nfawloq@geocities.jp',
          password: 'tLF9olij6Lb',
          passwordConfirmation: 'tLF9olij6Lb',
          bio: 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia',
          profileImage: 'https://i.pinimg.com/originals/67/e9/c3/67e9c30aafd02518c472ed907fb04afb.jpg',
          location: 'Broby',
          level: 'Mid-level',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Petronille',
          username: 'PetronilleByas',
          email: 'pbyasr@utexas.edu',
          password: 'xmRCxTUm',
          passwordConfirmation: 'xmRCxTUm',
          bio: 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in',
          profileImage: 'https://i.pinimg.com/originals/53/52/b2/5352b28cbeee079560e5773fb9514946.png',
          location: 'Orong',
          level: 'Junior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Renie',
          username: 'RenieWhittek',
          email: 'rwhitteks@posterous.com',
          password: 'Sae6dbBLhVs',
          passwordConfirmation: 'Sae6dbBLhVs',
          bio: 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit',
          profileImage: 'https://i.pinimg.com/originals/e5/39/f1/e539f1a9d0bef86fa42f348446353486.jpg',
          location: 'Jeberos',
          level: 'Junior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Darsey',
          username: 'DarseyAbramzon',
          email: 'dabramzont@symantec.com',
          password: 'atlPnN',
          passwordConfirmation: 'atlPnN',
          bio: 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales',
          profileImage: 'https://i.pinimg.com/474x/b4/fc/cc/b4fccc8af248028ac48839626c0a7120--american-man-american-actors.jpg',
          location: 'Uścimów Stary',
          level: 'Junior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Michal',
          username: 'MichalWetter',
          email: 'mwetteru@amazon.co.jp',
          password: 'wRBSIgb8YF',
          passwordConfirmation: 'wRBSIgb8YF',
          bio: 'id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu',
          profileImage: 'https://www.bing.com/th/id/OIP.JiMIAWrzGEeKsZRlHR7QiAHaKX?w=172&h=240&c=7&o=5&dpr=2&pid=1.7',
          location: 'Xinsheng',
          level: 'Junior',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Lissi',
          username: 'LissiHindrick',
          email: 'lhindrickv@deliciousdays.com',
          password: 'r6O4zEkI0',
          passwordConfirmation: 'r6O4zEkI0',
          bio: 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus',
          profileImage: 'https://d3fc22kf489ohb.cloudfront.net/assets/426e9538a23b570b87f8570788f91e1844658718/static/media/get-paid.c6ae90b5.jpg',
          location: 'Zhengguo',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Valencia',
          username: 'ValenciaLiley',
          email: 'vlileyw@yellowbook.com',
          password: '7eXIeqyX4P',
          passwordConfirmation: '7eXIeqyX4P',
          bio: 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate',
          profileImage: 'https://www.bing.com/th/id/OIP.EPCigxeAh1r1kdyOG1lTBgHaJP?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Jangkungkusumo',
          level: 'Mid-level',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Horatia',
          username: 'HoratiaYerby',
          email: 'hyerbyx@google.nl',
          password: 'tPY74YH',
          passwordConfirmation: 'tPY74YH',
          bio: 'erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin',
          profileImage: 'https://www.bing.com/th/id/OIP.07jvNRxmIUJ2Gva39d2_AQHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Pergan',
          level: 'Mid-level',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Meridith',
          username: 'MeridithGogerty',
          email: 'mgogertyy@cmu.edu',
          password: 'Z1MUZeT1f',
          passwordConfirmation: 'Z1MUZeT1f',
          bio: 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem',
          profileImage: 'https://www.bing.com/th/id/OIP.MtTGdVycsytv7vuoGNbOKwHaJD?w=172&h=210&c=7&o=5&dpr=2&pid=1.7',
          location: 'Cungapmimbo',
          level: 'Junior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Vale',
          username: 'ValeWemyss',
          email: 'vwemyssz@t.co',
          password: '6eduIv',
          passwordConfirmation: '6eduIv',
          bio: 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa',
          profileImage: 'https://www.bing.com/th/id/OIP.hzZrWvrJDRye43hMTGsArQHaLL?w=172&h=260&c=7&o=5&dpr=2&pid=1.7',
          location: 'Brooklyn',
          level: 'Junior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Joly',
          username: 'JolyAshplant',
          email: 'jashplant10@usnews.com',
          password: 'NknFspzZnAN7',
          passwordConfirmation: 'NknFspzZnAN7',
          bio: 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia',
          profileImage: 'https://www.bing.com/th/id/OIP.5TBmZeMQf76V_FEFYm132QHaE8?w=172&h=115&c=7&o=5&dpr=2&pid=1.7',
          location: 'Pedreira',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Rozanna',
          username: 'RozannaGreenlees',
          email: 'rgreenlees11@mac.com',
          password: 'TcVFhSWVwl',
          passwordConfirmation: 'TcVFhSWVwl',
          bio: 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor',
          profileImage: 'https://www.bing.com/th/id/OIP.o_Sv02tD2cNxl3moN3gnHQHaLE?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Pingshan',
          level: 'Junior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Maurine',
          username: 'MaurineBahlmann',
          email: 'mbahlmann12@furl.net',
          password: 'zjJeOl',
          passwordConfirmation: 'zjJeOl',
          bio: 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit',
          profileImage: 'https://www.bing.com/th/id/OIP.Az8vp3lQNO1riPShpIHMrgHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Riangbaring',
          level: 'Junior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Starla',
          username: 'StarlaNinnoli',
          email: 'sninnoli13@addthis.com',
          password: 'swinwG1P',
          passwordConfirmation: 'swinwG1P',
          bio: 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id',
          profileImage: 'https://www.bing.com/th/id/OIP.4HTyAcdfHpDTYjXU-MWGEwHaK8?w=172&h=255&c=7&o=5&dpr=2&pid=1.7',
          location: 'Sarmīn',
          level: 'Junior',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Charmaine',
          username: 'CharmaineKindell',
          email: 'ckindell14@bandcamp.com',
          password: 'A9A8ZFVgPX',
          passwordConfirmation: 'A9A8ZFVgPX',
          bio: 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam',
          profileImage: 'https://www.bing.com/th/id/OIP.-fi9aMKHvriURK0Q_SZyKwHaHo?w=172&h=177&c=7&o=5&dpr=2&pid=1.7',
          location: 'Huangcai',
          level: 'Mid-level',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Sonya',
          username: 'SonyaAntonowicz',
          email: 'santonowicz15@technorati.com',
          password: 'W7CnvD',
          passwordConfirmation: 'W7CnvD',
          bio: 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus',
          profileImage: 'https://www.bing.com/th/id/OIP.9FZK4bewA1jXchbVTLOuQQAAAA?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Arcos',
          level: 'Junior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Klarrisa',
          username: 'KlarrisaTumielli',
          email: 'ktumielli16@netvibes.com',
          password: 'SZfHB2ANIi',
          passwordConfirmation: 'SZfHB2ANIi',
          bio: 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut',
          profileImage: 'https://www.bing.com/th/id/OIP.nIFsmXpJwPHeZXxh8xXkQgHaK_?w=172&h=255&c=7&o=5&dpr=2&pid=1.7',
          location: 'Potoru',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Corrine',
          username: 'CorrineVaulkhard',
          email: 'cvaulkhard17@shutterfly.com',
          password: 'gEHuCUlaVH',
          passwordConfirmation: 'gEHuCUlaVH',
          bio: 'donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut',
          profileImage: 'https://www.bing.com/th/id/OIP.EME62cs02N6P5kIpuEzf7QHaLn?w=172&h=270&c=7&o=5&dpr=2&pid=1.7',
          location: 'Huxu',
          level: 'Junior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Willie',
          username: 'WillieHarvett',
          email: 'wharvett18@zdnet.com',
          password: '2osIQb2hAMn',
          passwordConfirmation: '2osIQb2hAMn',
          bio: 'at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin',
          profileImage: 'https://www.bing.com/th/id/OIP.kJiACrpPjwqZNQhG5HfB2wHaHa?w=172&h=172&c=7&o=5&dpr=2&pid=1.7',
          location: 'Guluoshan',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Stephi',
          username: 'StephiKencott',
          email: 'skencott19@xinhuanet.com',
          password: 'TjLnmj1k2CA',
          passwordConfirmation: 'TjLnmj1k2CA',
          bio: 'nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas',
          profileImage: 'https://www.bing.com/th/id/OIP.gw3GzkpLjht1ho4O886KpQHaF7?w=172&h=137&c=7&o=5&dpr=2&pid=1.7',
          location: 'Tiền Hải',
          level: 'Senior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Keri',
          username: 'KeriItzik',
          email: 'kitzik1a@eventbrite.com',
          password: 'a6jrjA9VL',
          passwordConfirmation: 'a6jrjA9VL',
          bio: 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum',
          profileImage: 'https://www.bing.com/th/id/OIP.Ze67QOZvf31Z94tHKnW2LwHaLG?w=172&h=257&c=7&o=5&dpr=2&pid=1.7',
          location: 'Calinog',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Salomi',
          username: 'SalomiGillmor',
          email: 'sgillmor1b@wired.com',
          password: 'BbW6RMSah',
          passwordConfirmation: 'BbW6RMSah',
          bio: 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam',
          profileImage: 'https://www.bing.com/th/id/OIP.GIqR35B1Rp5rlnXhaHUQZwHaLH?w=172&h=259&c=7&o=5&dpr=2&pid=1.7',
          location: 'General Alvear',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Ibby',
          username: 'IbbyMaymand',
          email: 'imaymand1c@vinaora.com',
          password: 'avnXgryzgtl',
          passwordConfirmation: 'avnXgryzgtl',
          bio: 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse',
          profileImage: 'https://www.bing.com/th/id/OIP.HmTmZBkTcFUXhUx3FvJDpgHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Belogorskīy',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Adan',
          username: 'AdanCawtheray',
          email: 'acawtheray1d@globo.com',
          password: 's3nqGFqa',
          passwordConfirmation: 's3nqGFqa',
          bio: 'nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum',
          profileImage: 'https://www.bing.com/th/id/OIP.kwSazK3NT40VfAZslgpwMgHaE8?w=172&h=115&c=7&o=5&dpr=2&pid=1.7',
          location: 'Gómfoi',
          level: 'Senior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Evie',
          username: 'EvieDanniel',
          email: 'edanniel1e@ycombinator.com',
          password: 'orHypQm',
          passwordConfirmation: 'orHypQm',
          bio: 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec',
          profileImage: 'https://www.bing.com/th/id/OIP.hbD2LVwXJBIjmIjiqV0TiwHaKh?w=172&h=245&c=7&o=5&dpr=2&pid=1.7',
          location: 'Hernández',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Emelda',
          username: 'EmeldaKarlsson',
          email: 'ekarlsson1f@hugedomains.com',
          password: 'hQq5jFY',
          passwordConfirmation: 'hQq5jFY',
          bio: 'pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in',
          profileImage: 'https://www.bing.com/th/id/OIP.7YybHIPil4YWnVtz3FpLZgHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Budakovo',
          level: 'Senior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Raphaela',
          username: 'RaphaelaWestbrook',
          email: 'rwestbrook1g@devhub.com',
          password: '4yrOtfSO',
          passwordConfirmation: '4yrOtfSO',
          bio: 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu',
          profileImage: 'https://www.bing.com/th/id/OIP.R5vgTC_aaX1zxvPf0tHbzQHaLJ?w=172&h=259&c=7&o=5&dpr=2&pid=1.7',
          location: 'Regente Feijó',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Reggi',
          username: 'ReggiGoodin',
          email: 'rgoodin1h@pinterest.com',
          password: 'TvoMyoC',
          passwordConfirmation: 'TvoMyoC',
          bio: 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem',
          profileImage: 'https://www.bing.com/th/id/OIP.5ku-3W2zy0GhfarPmDkIowHaIT?w=172&h=192&c=7&o=5&dpr=2&pid=1.7',
          location: 'Jietou',
          level: 'Mid-level',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Dulci',
          username: 'DulciWhiterod',
          email: 'dwhiterod1i@sogou.com',
          password: 'cEK7eQ2xQXv',
          passwordConfirmation: 'cEK7eQ2xQXv',
          bio: 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam',
          profileImage: 'https://www.bing.com/th/id/OIP.YnOK9yUlV6gB6vpiGzKPFgHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Kentongan',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Carey',
          username: 'CareyLiepins',
          email: 'cliepins1j@trellian.com',
          password: '8D7aYHjvvig',
          passwordConfirmation: '8D7aYHjvvig',
          bio: 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis',
          profileImage: 'https://www.bing.com/th/id/OIP.tyXBrkhuh9cTSxV-tFK9kwHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Puerto Padre',
          level: 'Junior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Emelyne',
          username: 'EmelyneCutbirth',
          email: 'ecutbirth1k@berkeley.edu',
          password: 'wVxWuS8v',
          passwordConfirmation: 'wVxWuS8v',
          bio: 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede',
          profileImage: 'https://www.bing.com/th/id/OIP.Is7uUOhV8blGGczUF42JbQHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Skutskär',
          level: 'Mid-level',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Darcey',
          username: 'DarceyHylden',
          email: 'dhylden1l@google.pl',
          password: 'tQU7ML2VXvrA',
          passwordConfirmation: 'tQU7ML2VXvrA',
          bio: 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa',
          profileImage: 'https://www.bing.com/th/id/OIP.hWhklSnCZ0UKaoGE5VTdsAHaE6?w=172&h=114&c=7&o=5&dpr=2&pid=1.7',
          location: 'Katabu',
          level: 'Junior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Catherin',
          username: 'CatherinBorn',
          email: 'cborn1m@hugedomains.com',
          password: 'arQcdwouA',
          passwordConfirmation: 'arQcdwouA',
          bio: 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus',
          profileImage: 'https://www.bing.com/th/id/OIP.h2iE5hMwLTCftwYG7nVswgHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'La Curva',
          level: 'Junior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Flossy',
          username: 'FlossyTinwell',
          email: 'ftinwell1n@google.ru',
          password: 'Ce1rmzc3',
          passwordConfirmation: 'Ce1rmzc3',
          bio: 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis',
          profileImage: 'https://www.bing.com/th/id/OIP.uymFmpVncD0HKYhfjQjBwQHaFk?w=172&h=129&c=7&o=5&dpr=2&pid=1.7',
          location: 'Washington',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Reba',
          username: 'RebaStammler',
          email: 'rstammler1o@gravatar.com',
          password: 'VEHFg4',
          passwordConfirmation: 'VEHFg4',
          bio: 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna',
          profileImage: 'https://www.bing.com/th/id/OIP.K8NGcb6Y2_O009dbnMn-iQAAAA?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Musawa',
          level: 'Junior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Jacenta',
          username: 'JacentaHauxley',
          email: 'jhauxley1p@globo.com',
          password: 'PphgWYLelb',
          passwordConfirmation: 'PphgWYLelb',
          bio: 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et',
          profileImage: 'https://www.bing.com/th/id/OIP.yfxTqTny53AdTEggO2CGDwAAAA?w=172&h=173&c=7&o=5&dpr=2&pid=1.7',
          location: 'Santa Maria',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Carmel',
          username: 'CarmelPywell',
          email: 'cpywell1q@hc360.com',
          password: 'NYpla8je',
          passwordConfirmation: 'NYpla8je',
          bio: 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius',
          profileImage: 'https://www.bing.com/th/id/OIP.mJpwL22BwZfzaRYVCPqHpQHaKX?w=172&h=240&c=7&o=5&dpr=2&pid=1.7',
          location: 'Jinchuan',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Dorelia',
          username: 'DoreliaBatha',
          email: 'dbatha1r@nymag.com',
          password: 'XcIAaY',
          passwordConfirmation: 'XcIAaY',
          bio: 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam',
          profileImage: 'https://www.bing.com/th/id/OIP.vOeymv1jn_5pFG6f0ws2ygHaHa?w=172&h=172&c=7&o=5&dpr=2&pid=1.7',
          location: 'Samut Sakhon',
          level: 'Junior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Doralin',
          username: 'DoralinAlchin',
          email: 'dalchin1s@ameblo.jp',
          password: 'A34nTZ7ap',
          passwordConfirmation: 'A34nTZ7ap',
          bio: 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean',
          profileImage: 'https://www.bing.com/th/id/OIP.xHRF7VGNSGQPWQvTeFNqtAHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Hengxi',
          level: 'Senior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Ethel',
          username: 'EthelGrinov',
          email: 'egrinov1t@mediafire.com',
          password: 'nqE0JQe1Kx3',
          passwordConfirmation: 'nqE0JQe1Kx3',
          bio: 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum',
          profileImage: 'https://www.bing.com/th/id/OIP.HcIHiwFLZmQUNsoDJ__f2AHaJ4?w=172&h=229&c=7&o=5&dpr=2&pid=1.7',
          location: 'Przemyśl',
          level: 'Senior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Lucretia',
          username: 'LucretiaBurhouse',
          email: 'lburhouse1u@cbslocal.com',
          password: 'NVoUocRlX35',
          passwordConfirmation: 'NVoUocRlX35',
          bio: 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere',
          profileImage: 'https://www.bing.com/th/id/OIP.sRofl-fvyhM-4KyB4EdJAAHaLG?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Danchang',
          level: 'Senior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Britt',
          username: 'BrittClemits',
          email: 'bclemits1v@livejournal.com',
          password: '3ENQv4VjyZBm',
          passwordConfirmation: '3ENQv4VjyZBm',
          bio: 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque',
          profileImage: 'https://www.bing.com/th/id/OIP.h8fI6uQCeCJnv9JIOZAgKgHaGN?w=172&h=144&c=7&o=5&dpr=2&pid=1.7',
          location: 'Hejiaping',
          level: 'Mid-level',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Concettina',
          username: 'Concettina SaintePaul',
          email: 'csainte1w@icq.com',
          password: 'i4IdsSF7Ly',
          passwordConfirmation: 'i4IdsSF7Ly',
          bio: 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna',
          profileImage: 'https://www.bing.com/th/id/OIP.rc0lh6-srYrkDh8262etfAHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Adir',
          level: 'Mid-level',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Gay',
          username: 'GayBontoft',
          email: 'gbontoft1x@youtube.com',
          password: 'VqbQZS5Vc',
          passwordConfirmation: 'VqbQZS5Vc',
          bio: 'adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis',
          profileImage: 'https://www.bing.com/th/id/OIP.KrR9WmxI1w-yTapqANYHuwHaJy?w=172&h=227&c=7&o=5&dpr=2&pid=1.7',
          location: 'Pando',
          level: 'Senior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Lee',
          username: 'LeeWalkinshaw',
          email: 'lwalkinshaw1y@cnn.com',
          password: 'Y34LM4e1Arpu',
          passwordConfirmation: 'Y34LM4e1Arpu',
          bio: 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla',
          profileImage: 'https://www.bing.com/th/id/OIP.TpRrDdtsu4JyO9wJlyoeJgHaLD?w=172&h=257&c=7&o=5&dpr=2&pid=1.7',
          location: 'Paoay',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Muriel',
          username: 'Muriel DellaScala',
          email: 'mdella1z@cocolog-nifty.com',
          password: 'JCFXWu',
          passwordConfirmation: 'JCFXWu',
          bio: 'vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra',
          profileImage: 'https://www.bing.com/th/id/OIP.ukJ87xI4wTZdCrgTgacaMwHaHb?w=172&h=173&c=7&o=5&dpr=2&pid=1.7',
          location: 'Baihe',
          level: 'Senior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Lynne',
          username: 'LynneSleit',
          email: 'lsleit20@house.gov',
          password: 'nbzby51YKXK',
          passwordConfirmation: 'nbzby51YKXK',
          bio: 'aliquam sit amet diam in magna bibendum imperdiet nullam orci pede',
          profileImage: 'https://www.bing.com/th/id/OIP.XOuq2tVtArwyE6mzRUdYvgHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Sokol’skoye',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Pansie',
          username: 'PansieJansa',
          email: 'pjansa21@com.com',
          password: 'VpBxV6fhX',
          passwordConfirmation: 'VpBxV6fhX',
          bio: 'cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem',
          profileImage: 'https://www.bing.com/th/id/OIP.FKGLlHHI4lYftODGKLlU3gHaLG?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Margahayu',
          level: 'Junior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Misha',
          username: 'MishaCrosser',
          email: 'mcrosser22@usatoday.com',
          password: 'DaGXRebZ',
          passwordConfirmation: 'DaGXRebZ',
          bio: 'non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in',
          profileImage: 'https://www.bing.com/th/id/OIP.XA1xVVonXajaXNkfCrmGiwHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Lyon',
          level: 'Junior',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Haley',
          username: 'HaleyPrestedge',
          email: 'hprestedge23@hexun.com',
          password: 'zWUuiL',
          passwordConfirmation: 'zWUuiL',
          bio: 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio',
          profileImage: 'https://www.bing.com/th/id/OIP.6vL-D5o1SoAkZ5jzrjSKBQDLEy?w=172&h=259&c=7&o=5&dpr=2&pid=1.7',
          location: 'Qianzhou',
          level: 'Senior',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Shannah',
          username: 'ShannahPhillips',
          email: 'sphillips24@sphinn.com',
          password: 'SJYRDsaSp0',
          passwordConfirmation: 'SJYRDsaSp0',
          bio: 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id',
          profileImage: 'https://www.bing.com/th/id/OIP.fPuTRf22pATPdRU72ZwoXAHaE8?w=172&h=115&c=7&o=5&dpr=2&pid=1.7',
          location: 'Tamandaré',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Hanna',
          username: 'HannaRiolfo',
          email: 'hriolfo25@ebay.com',
          password: 'nH1I1Pdz',
          passwordConfirmation: 'nH1I1Pdz',
          bio: 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at',
          profileImage: 'https://www.bing.com/th/id/OIP.7M749ajeZH1ISG6MiAdpAQHaLQ?w=172&h=261&c=7&o=5&dpr=2&pid=1.7',
          location: 'San Vicente',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Samaria',
          username: 'SamariaHun',
          email: 'shun26@unc.edu',
          password: 'ylDRfv5GZYE',
          passwordConfirmation: 'ylDRfv5GZYE',
          bio: 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero',
          profileImage: 'https://www.bing.com/th/id/OIP.11h6QwVvbQnt6iJqoTZk3QHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Tan Sum',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Danell',
          username: 'DanellGiordano',
          email: 'dgiordano27@google.de',
          password: '5HxH79dFWM',
          passwordConfirmation: '5HxH79dFWM',
          bio: 'nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris',
          profileImage: 'https://www.bing.com/th/id/OIP.CoYmMzKAdNhJIVArpY-IIwHaE8?w=172&h=115&c=7&o=5&dpr=2&pid=1.7',
          location: 'Osiek',
          level: 'Senior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Zara',
          username: 'ZaraBraney',
          email: 'zbraney28@1und1.de',
          password: 'eAKpbbIFuUV',
          passwordConfirmation: 'eAKpbbIFuUV',
          bio: 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut',
          profileImage: 'https://www.bing.com/th/id/OIP.XUF2Ow_6T2TTHgNlG018yQHaFj?w=172&h=129&c=7&o=5&dpr=2&pid=1.7',
          location: 'Bassar',
          level: 'Junior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Danya',
          username: 'DanyaBrumfield',
          email: 'dbrumfield29@admin.ch',
          password: 'yPh38Qrw44J',
          passwordConfirmation: 'yPh38Qrw44J',
          bio: 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum',
          profileImage: 'https://www.bing.com/th/id/OIP.XHZRLeuoTuK6ME0Lwg6swgHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Pointe-à-Pitre',
          level: 'Mid-level',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Theodosia',
          username: 'TheodosiaBidnall',
          email: 'tbidnall2a@is.gd',
          password: 'szTY9RFc',
          passwordConfirmation: 'szTY9RFc',
          bio: 'vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna',
          profileImage: 'https://www.bing.com/th/id/OIP.45TkkdJ1_95VSTVaENEtuwHaE8?w=172&h=114&c=7&o=5&dpr=2&pid=1.7',
          location: 'Jirjā',
          level: 'Senior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Ketty',
          username: 'KettyRamsey',
          email: 'kramsey2b@slashdot.org',
          password: 'EMgjhhU',
          passwordConfirmation: 'EMgjhhU',
          bio: 'quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla',
          profileImage: 'https://www.bing.com/th/id/OIP.nfVa6991a3AiGb-PBlvPaAHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Sarimukti Kaler',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Rikki',
          username: 'RikkiBenoit',
          email: 'rbenoit2c@yellowbook.com',
          password: '9YqmMVF5Og4',
          passwordConfirmation: '9YqmMVF5Og4',
          bio: 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent',
          profileImage: 'https://www.bing.com/th/id/OIP.3z2Y7DW7XMj-teVHRsav3gHaE6?w=172&h=114&c=7&o=5&dpr=2&pid=1.7',
          location: 'Uujim',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Shaun',
          username: 'ShaunGove',
          email: 'sgove2d@nationalgeographic.com',
          password: '1Gis1bGJmci',
          passwordConfirmation: '1Gis1bGJmci',
          bio: 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at',
          profileImage: 'https://www.bing.com/th/id/OIP.ozmUuspFlvi0wHFU53mvnAHaF7?w=172&h=137&c=7&o=5&dpr=2&pid=1.7',
          location: 'Jincheng',
          level: 'Senior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Ina',
          username: 'InaRonnay',
          email: 'ironnay2e@storify.com',
          password: '3xw97f1a7MX',
          passwordConfirmation: '3xw97f1a7MX',
          bio: 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est',
          profileImage: 'https://www.bing.com/th/id/OIP.taTkP5OfVzpIeM-cQ678AAHaE8?w=172&h=115&c=7&o=5&dpr=2&pid=1.7',
          location: 'Leuweheq',
          level: 'Mid-level',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Shannah',
          username: 'ShannahMoncreiffe',
          email: 'smoncreiffe2f@google.ca',
          password: 'j76aw2mPgYu',
          passwordConfirmation: 'j76aw2mPgYu',
          bio: 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim',
          profileImage: 'https://www.bing.com/th/id/OIP.eDb7gcgd9ERkBdj-4DkdcgHaJa?w=172&h=219&c=7&o=5&dpr=2&pid=1.7',
          location: 'Sūq al Khamīs',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Cordelie',
          username: 'CordelieBalk',
          email: 'cbalk2g@cdbaby.com',
          password: 'E1qYgUN8X',
          passwordConfirmation: 'E1qYgUN8X',
          bio: 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras',
          profileImage: 'https://www.bing.com/th/id/OIP.oXjgO8M9UD1UGfqMzwDUwAHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Larreynaga',
          level: 'Senior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Cary',
          username: 'CaryStains',
          email: 'cstains2h@arizona.edu',
          password: 'vWjmjS',
          passwordConfirmation: 'vWjmjS',
          bio: 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla',
          profileImage: 'https://www.bing.com/th/id/OIP.a1zE-fvhzAAi9GKfxNnT2gHaKW?w=172&h=240&c=7&o=5&dpr=2&pid=1.7',
          location: 'Galis',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Beatriz',
          username: 'BeatrizRowlings',
          email: 'browlings2i@free.fr',
          password: '5Ym5vh1',
          passwordConfirmation: '5Ym5vh1',
          bio: 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin',
          profileImage: 'https://www.bing.com/th/id/OIP.p6V-V8qB6zLZZx8XW6eu-gHaE7?w=172&h=114&c=7&o=5&dpr=2&pid=1.7',
          location: 'Alis',
          level: 'Senior',
          skills: { skill: 'Quality Control' }
        },
        {
          name: 'Cornelle',
          username: 'CornelleCreddon',
          email: 'ccreddon2j@github.com',
          password: 'CExS996',
          passwordConfirmation: 'CExS996',
          bio: 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis',
          profileImage: 'https://www.bing.com/th/id/OIP.VDK1I1iMnQoj1y9xzZiDKgHaE8?w=172&h=115&c=7&o=5&dpr=2&pid=1.7',
          location: 'Gontar',
          level: 'Senior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Rosemaria',
          username: 'Rosemaria DeAngelis',
          email: 'rde2k@xrea.com',
          password: 'XKqoY8',
          passwordConfirmation: 'XKqoY8',
          bio: 'est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl',
          profileImage: 'https://www.bing.com/th/id/OIP.ju7ceP73E26R7sopz_LQMgHaKk?w=172&h=245&c=7&o=5&dpr=2&pid=1.7',
          location: 'Ishigaki',
          level: 'Senior',
          skills: { skill: 'Quick Thinking' }
        },
        {
          name: 'Lillian',
          username: 'LillianGlentz',
          email: 'lglentz2l@ucoz.ru',
          password: 'WDgg8J9bbqa4',
          passwordConfirmation: 'WDgg8J9bbqa4',
          bio: 'eget semper rutrum nulla nunc purus phasellus in felis donec',
          profileImage: 'https://www.bing.com/th/id/OIP.eNOviyeydmATsvPAY5wziAHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Gogosuket',
          level: 'Mid-level',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Zondra',
          username: 'ZondraLammertz',
          email: 'zlammertz2m@mlb.com',
          password: 'KEvJFWLxO8',
          passwordConfirmation: 'KEvJFWLxO8',
          bio: 'non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus',
          profileImage: 'https://www.bing.com/th/id/OIP.sTf4hsyCBLJOWhYhmH2PIgHaLH?w=172&h=258&c=7&o=5&dpr=2&pid=1.7',
          location: 'Yulin',
          level: 'Mid-level',
          skills: { skill: 'Magazine Design' }
        },
        {
          name: 'Rakel',
          username: 'RakelTedahl',
          email: 'rtedahl2n@wordpress.org',
          password: 'NS3kwhi94Kvd',
          passwordConfirmation: 'NS3kwhi94Kvd',
          bio: 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum',
          profileImage: 'https://www.bing.com/th/id/OIP.IMZxfUcgMfcSYiOm6G8juQAAAA?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'San Antonio',
          level: 'Senior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Avis',
          username: 'AvisHeavy',
          email: 'aheavy2o@unesco.org',
          password: 'Qp66E45q',
          passwordConfirmation: 'Qp66E45q',
          bio: 'diam cras pellentesque volutpat dui maecenas tristique est et tempus semper',
          profileImage: 'https://www.bing.com/th/id/OIP.Kb7iz39WKv9l9HLGgkpEegAAAA?w=166&h=250&c=7&o=5&dpr=2&pid=1.7',
          location: 'Arroyo Salado',
          level: 'Senior',
          skills: { skill: 'Illustration' }
        },
        {
          name: 'Heath',
          username: 'HeathWhitwham',
          email: 'hwhitwham2p@shop-pro.jp',
          password: '8ue5dmjmg1m',
          passwordConfirmation: '8ue5dmjmg1m',
          bio: 'ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at',
          profileImage: 'https://www.bing.com/th/id/OIP.SG20JD2lV055DzDauDJ6TwHaE8?w=172&h=115&c=7&o=5&dpr=2&pid=1.7',
          location: 'Andapa',
          level: 'Junior',
          skills: { skill: 'JavaScript' }
        },
        {
          name: 'Lexis',
          username: 'LexisAloshikin',
          email: 'laloshikin2q@w3.org',
          password: 'w6i0dmUTwy',
          passwordConfirmation: 'w6i0dmUTwy',
          bio: 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo',
          profileImage: 'https://www.bing.com/th/id/OIP.w7lltchtK3cPkgfXvaDO-gHaHa?w=172&h=172&c=7&o=5&dpr=2&pid=1.7',
          location: 'Xushangqiao',
          level: 'Senior',
          skills: { skill: 'Quicktime' }
        },
        {
          name: 'Essy',
          username: 'EssyMacGorley',
          email: 'emacgorley2r@house.gov',
          password: 'rvo8nm',
          passwordConfirmation: 'rvo8nm',
          bio: 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non',
          profileImage: 'https://www.bing.com/th/id/OIP.djiqvB2svaklq38MOMAHDgHaJQ?w=172&h=215&c=7&o=5&dpr=2&pid=1.7',
          location: 'Llano de Piedra',
          level: 'Junior',
          skills: { skill: 'Quality Control' }
        }
      ])
    })
    .then(createdUser => {
      console.log(`${createdUser.length} users have been created`)
      return Project.create([
        {
          name: 'Project 1',
          owner: createdUser[0],
          collaborators: [createdUser[0]],
          description: 'This is a description of project 1',
          location: 'Glasgow',
          images: ['https://www.bing.com/th/id/OIP.fZwKVV51MO_hyk3iHj4EegHaE6?w=252&h=167&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.1hKUtMJ4rvt78aHxMt8pggHaLa?w=147&h=203&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Project 2',
          owner: createdUser[1],
          collaborators: [createdUser[1],createdUser[0],createdUser[2]],
          description: 'This is a description of project 2',
          location: 'Glasgow',
          images: ['https://www.bing.com/th/id/OIP.uDta4Xkn5BYT-toxye1M4AHaES?w=290&h=167&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.qB8UFs-FMbfJOSc55Rs0UgHaFj?w=286&h=203&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Project 3',
          owner: createdUser[3],
          collaborators: [createdUser[3],createdUser[1]],
          description: 'This is a description of project 3',
          location: 'Glasgow',
          images: ['https://www.bing.com/th/id/OIP.xGLvUR6OJFttNtiNtu6FYwHaFj?w=222&h=167&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.QR7OlV6umVk87hu_o0KjIwHaEq?w=257&h=161&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Project 4',
          owner: createdUser[2],
          collaborators: [createdUser[2],createdUser[0],createdUser[1]],
          description: 'This is a description of project 4',
          location: 'Glasgow',
          images: ['https://www.bing.com/th/id/OIP.cc1K8H52jR4s6NEmhjDz0wHaEK?w=297&h=167&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.e__B0D-i4kUxMuQPBsZSogHaE3?w=245&h=161&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Veribet',
          owner: createdUser[9],
          collaborators: createdUser[9],
          description: 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis',
          location: 'Junaynat Raslān',
          images: ['https://www.bing.com/th/id/OIP.m25iP-3nU74ZMm3So-L_WQHaFj?w=235&h=174&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.ace9tGo_-0QrAKmEgGrN-AHaEo?w=259&h=161&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: false,
          likes: []
        },
        {
          name: 'Hgfdcsr',
          owner: createdUser[13],
          collaborators: createdUser[13],
          description: 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id',
          location: 'Haoxin',
          images: ['https://www.bing.com/th/id/OIP.kd7jh5sJyn9Io9LTzfcsFgHaFj?w=236&h=174&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.MbvGVBCTD37NlXHEYGcn3AHaDi?w=299&h=143&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Andalax',
          owner: createdUser[0],
          collaborators: createdUser[0],
          description: 'sed tincidunt eu felis fusce posuere felis sed lacus morbi',
          location: 'Vicente Guerrero',
          images: ['https://www.bing.com/th/id/OIP.zawqJPKkJk535oXy4wPBcQAAAA?w=119&h=174&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.Ogbyrpih3esa7A-YduXTNAHaBT?w=287&h=63&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Vagram',
          owner: createdUser[2],
          collaborators: createdUser[2],
          description: 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula',
          location: 'Esuk Oron',
          images: ['https://www.bing.com/th/id/OIP.LBHYJDLFKDTYNiGaPn6ZQQHaE8?w=265&h=174&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.GO6vgOnlIHF5JUJ9ZXjMOAHaJ_?w=169&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Domainer',
          owner: createdUser[0],
          collaborators: createdUser[0],
          description: 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices',
          location: 'Khadīr',
          images: ['https://www.bing.com/th/id/OIP.cgaQohYei1Z7ST9YDoYWNwHaE8?w=198&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.RjEwQhiuzzC4AHMAoj30LwHaFB?w=211&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Bigtax',
          owner: createdUser[7],
          collaborators: createdUser[7],
          description: 'pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac',
          location: 'Novovarshavka',
          images: ['https://www.bing.com/th/id/OIP.WORcHAzdEn6DRl3TIWGFHgHaFj?w=177&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.dMCZoaNWyaVWTr8mC7NF_QHaLH?w=169&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Job',
          owner: createdUser[14],
          collaborators: createdUser[14],
          description: 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat',
          location: 'Motygino',
          images: ['https://www.bing.com/th/id/OIP.zkKbxjm4950srG2CyaT0mwHaE8?w=198&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.I66RIxJHsNv7xErszPIjlgHaE8?w=213&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Greenlam',
          owner: createdUser[13],
          collaborators: createdUser[13],
          description: 'amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis',
          location: 'Zhuhong',
          images: ['https://www.bing.com/th/id/OIP.3i8qdOPMg9lWJDpUtUgdKAHaE7?w=300&h=199&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.jg7rnJZ77aH_EitAOQsfYAHaFj?w=226&h=166&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Latlux',
          owner: createdUser[5],
          collaborators: createdUser[5],
          description: 'magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus',
          location: 'Songgang',
          images: ['https://www.bing.com/th/id/OIP.JtJuDM9tH6nTwm5u6wU1fgHaFj?w=288&h=211&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.oLCGm-anX5pJQ9j0NacoIgHaCq?w=300&h=107&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'Sonair',
          owner: createdUser[8],
          collaborators: createdUser[8],
          description: 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu',
          location: 'Zhongxing',
          images: ['https://www.bing.com/th/id/OIP.vnLPIP7BlOiKrtaV1W2S7gHaE6?w=300&h=199&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP._agvsJDnMcFx4fkej3hiNgHaCh?w=299&h=102&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'gdsrfesdbfhn',
          owner: createdUser[0],
          collaborators: createdUser[0],
          description: 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus',
          location: 'Ouango',
          images: ['https://www.bing.com/th/id/OIP.KcUpOkxUATGwym5YqMNG3AHaKz?w=153&h=211&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.wMnt2dj3ZbA9B9cCLx2NNQHaFj?w=226&h=166&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Cookley',
          owner: createdUser[4],
          collaborators: createdUser[4],
          description: 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat',
          location: 'Vinica',
          images: ['https://www.bing.com/th/id/OIP.mAc0S7rKeLtuylSPczHo5AHaFj?w=253&h=186&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.p6-p5i4d5_H66hs2XfWTzQHaFj?w=273&h=195&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Alphazap',
          owner: createdUser[2],
          collaborators: createdUser[2],
          description: 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui',
          location: 'Swindon',
          images: ['https://www.bing.com/th/id/OIP.5kXKeJO6ZAx9Y1OB9SLP_AHaEI?w=300&h=167&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.SSqnh-ARHgrLrf4vuIDpGgAAAA?w=212&h=159&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Duobam',
          owner: createdUser[6],
          collaborators: createdUser[6],
          description: 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan',
          location: 'Lasi Dua',
          images: ['https://www.bing.com/th/id/OIP.9-Y-bKk2cRnBkJd6kt3nLAHaQB?w=122&h=186&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.WPPJ02DteJTIlx2bhUdTdwHaGQ?w=246&h=195&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: false,
          likes: []
        },
        {
          name: 'It',
          owner: createdUser[7],
          collaborators: createdUser[7],
          description: 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet',
          location: 'Vesoul',
          images: ['https://www.bing.com/th/id/OIP.m30KGGy-wumgjO6-5bCvFQHaF7?w=240&h=186&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.CbbSxiXgXkkd7H8Bx0OctAHaEo?w=300&h=187&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'NHGFD',
          owner: createdUser[4],
          collaborators: createdUser[4],
          description: 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non',
          location: 'Nakhon Nayok',
          images: ['https://www.bing.com/th/id/OIP.viz2ne9gsxTRmo7syiEitwHaLf?w=127&h=186&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.UNuDKKnXC7iz-nT3pzRbxAHaE8?w=300&h=200&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Overhold',
          owner: createdUser[3],
          collaborators: createdUser[3],
          description: 'velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget',
          location: 'Changbai',
          images: ['https://www.bing.com/th/id/OIP.IG87EiRz_cTUkSWdTcjaYwHaFj?w=178&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.af_y0frtre_oJkVdmfkh3gHaFj?w=275&h=205&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Sonsing',
          owner: createdUser[12],
          collaborators: createdUser[12],
          description: 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel',
          location: 'Sinjhoro',
          images: ['https://www.bing.com/th/id/OIP.qIU6xJyJkmpQASOFPQl7ggHaC5?w=233&h=117&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.Wo3PJRSIQJptZmv95b9bSgHaHR?w=211&h=205&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'gadsfdfdfgftr',
          owner: createdUser[8],
          collaborators: createdUser[8],
          description: 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend',
          location: 'Tolosa',
          images: ['https://www.bing.com/th/id/OIP.IMmuN6Tt67kZ67HbFuy6dgHaFj?w=181&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.kqqmmhBXAZbq3Bau3ixOfQHaFj?w=275&h=205&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Temp',
          owner: createdUser[8],
          collaborators: createdUser[8],
          description: 'interdum mauris ullamcorper purus sit amet nulla quisque arcu libero',
          location: 'Donostia-San Sebastian',
          images: ['https://www.bing.com/th/id/OIP.tZWPy8kzEbvLKvwFAh1gLgHaEK?w=224&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.qVltj9u63AHvXuUG98m7jQHaCh?w=299&h=102&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'HTDGRAFS',
          owner: createdUser[0],
          collaborators: createdUser[0],
          description: 'diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat',
          location: 'Umpak',
          images: ['https://www.bing.com/th/id/OIP.FT874Qyso-UYGubHUZY9SQHaDF?w=233&h=124&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.PA98NxR_-IO_Iqf1VM2pVAHaFj?w=217&h=161&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Flowdesk',
          owner: createdUser[1],
          collaborators: createdUser[1],
          description: 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id',
          location: 'Hilotongan',
          images: ['https://www.bing.com/th/id/OIP.sAi-1vDy9vbs3laMlZlIVwHaEo?w=300&h=187&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.MnYj_D1-2VJVNvN92XZQcAHaDt?w=299&h=149&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Otcom',
          owner: createdUser[8],
          collaborators: createdUser[8],
          description: 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus',
          location: 'Kirovsk',
          images: ['https://www.bing.com/th/id/OIP.wYXQiKyxDvW1tUwhVEyjcQHaHa?w=219&h=206&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.Up4jEOkH3gn-P9-BIJfjXAHaE8?w=244&h=161&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Tampflex',
          owner: createdUser[13],
          collaborators: createdUser[13],
          description: 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem',
          location: 'Ekou',
          images: ['https://www.bing.com/th/id/OIP.l11s9xy_GbJm3ua1qOB9LAHaE1?w=300&h=195&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.W_-sPbPPEzmo19BgG4NfBAHaFj?w=241&h=181&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Quo Lux',
          owner: createdUser[12],
          collaborators: createdUser[12],
          description: 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat',
          location: 'Refojos',
          images: ['https://www.bing.com/th/id/OIP.QDBQjamX9PpDNIQTp6UdogHaHa?w=219&h=206&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.Nj60AACpldeIbWGkCtMR4AHaE8?w=272&h=181&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Toughjoyfax',
          owner: createdUser[14],
          collaborators: createdUser[14],
          description: 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus',
          location: 'Pará de Minas',
          images: ['https://www.bing.com/th/id/OIP.qaJPEutzx-Fs4cN-miV9RAHaEK?w=300&h=168&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.YCAQ8R3RopHsJh1hN-UvGgHaE6?w=274&h=181&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'Cardify',
          owner: createdUser[13],
          collaborators: createdUser[13],
          description: 'sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam',
          location: 'Daguo',
          images: ['https://www.bing.com/th/id/OIP.YnZ66O998W7SGbcrvSpqQgHaFj?w=224&h=168&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.-RSP4h_CR2NI3OBm6SeeKgHaE7?w=274&h=181&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'Jerry',
          owner: createdUser[14],
          collaborators: createdUser[14],
          description: 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus',
          location: 'Naḥf',
          images: ['https://www.bing.com/th/id/OIP.JHRV7s4p9Lv1TKifLz9iAgHaEw?w=262&h=168&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.xKGtgAtjRQvuWaf1hTxsDAHaEK?w=209&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Aerified',
          owner: createdUser[4],
          collaborators: createdUser[4],
          description: 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus',
          location: 'Cumanayagua',
          images: ['https://www.bing.com/th/id/OIP.AWyxQ_8XpsaqcuZcIgFL1gHaEo?w=275&h=168&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.-m4k_82UFKFO6lIQanhfJwAAAA?w=187&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: false,
          likes: []
        },
        {
          name: 'Kent',
          owner: createdUser[0],
          collaborators: createdUser[0],
          description: 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim',
          location: 'Avignon',
          images: ['https://www.bing.com/th/id/OIP.V7Uys1zbtIAwr9pH0gnv4QHaE8?w=193&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.wRb46xI5mMfT9gzL2How6wAAAA?w=176&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'Stringtough',
          owner: createdUser[2],
          collaborators: createdUser[2],
          description: 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam',
          location: 'Haoxinying',
          images: ['https://www.bing.com/th/id/OIP.oQQBua12gYMQIknmmzr2RgHaCI?w=234&h=86&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.6OW7kUG-Ec7cZhgyA2Bz3QHaEK?w=210&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'Y-find',
          owner: createdUser[6],
          collaborators: createdUser[6],
          description: 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id',
          location: 'Banzão',
          images: ['https://www.bing.com/th/id/OIP.-W8numHoXgwt87i2qqFl7wAAAA?w=180&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.QY5YFEJp3XweZI6Oi6y0LwHaEo?w=210&h=160&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: false,
          likes: []
        },
        {
          name: 'Prodder',
          owner: createdUser[6],
          collaborators: createdUser[6],
          description: 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor',
          location: 'Lakbok',
          images: ['https://www.bing.com/th/id/OIP.IW80txP5ZrV7TbUAO8qDywHaEo?w=207&h=160&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.kcf7Z78fgtDI2hIYpEc4nAHaEK?w=295&h=165&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: false,
          likes: []
        },
        {
          name: 'Bamity',
          owner: createdUser[8],
          collaborators: createdUser[8],
          description: 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at',
          location: 'Arnhem',
          images: ['https://www.bing.com/th/id/OIP.w7JYdjtAvHX6jVmzMGGLkAHaCv?w=235&h=111&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.tYV8BkaJHFDaPrJ5a9kv2AHaE7?w=249&h=165&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'Zaam-Dox',
          owner: createdUser[1],
          collaborators: createdUser[1],
          description: 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia',
          location: 'Wang Sai Phun',
          images: ['https://www.bing.com/th/id/OIP.N2pAB9_HzFRbYxIUnDiIkwHaEo?w=296&h=185&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.reSxsf3fBof6OO_PLMz5rwHaFa?w=225&h=165&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'Tempsoft',
          owner: createdUser[12],
          collaborators: createdUser[12],
          description: 'morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus',
          location: 'Şaḩneh',
          images: ['https://www.bing.com/th/id/OIP.VPGE-tJISw2O9TIrg8i8QgHaE8?w=278&h=185&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.hQbWTXLZwRW6VnP5oL3NRgHaEM?w=292&h=165&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        },
        {
          name: 'Zathin',
          owner: createdUser[2],
          collaborators: createdUser[2],
          description: 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula',
          location: 'Gualán',
          images: ['https://www.bing.com/th/id/OIP.P3Haag0jhX8PltnAS0RFPQHaGl?w=208&h=185&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.RuK2doMk3RT3a24EF-wL4gHaFj?w=257&h=193&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: true,
          likes: []
        },
        {
          name: 'HDGFSa',
          owner: createdUser[13],
          collaborators: createdUser[13],
          description: 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit',
          location: 'Duba',
          images: ['https://www.bing.com/th/id/OIP.rBMxqqiAURLOJbNyfm4BZwHaE7?w=279&h=185&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.dloZF95_N_zgKL_asVqtcQHaFj?w=257&h=193&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Namfix',
          owner: createdUser[6],
          collaborators: createdUser[6],
          description: 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui',
          location: 'Kasiyan',
          images: ['https://www.bing.com/th/id/OIP.L3mzlGUXU0Xm5BmX8DC9_gHaEQ?w=300&h=172&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.8Wr7POFP81zKJspEMdvF6QHaFj?w=257&h=193&c=7&o=5&dpr=2&pid=1.7'],
          completed: true,
          recruiting: false,
          likes: []
        },
        {
          name: 'Flexidy',
          owner: createdUser[10],
          collaborators: createdUser[10],
          description: 'non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa',
          location: 'Bang Krathum',
          images: ['https://www.bing.com/th/id/OIP.P4J6EwtV7KSaK5_YGyy6UQHaE8?w=300&h=200&c=7&o=5&dpr=2&pid=1.7', 'https://www.bing.com/th/id/OIP.kqgyk22QUequMZXA96StTAHaE8?w=290&h=193&c=7&o=5&dpr=2&pid=1.7'],
          completed: false,
          recruiting: true,
          likes: []
        }
      ])
    })
    .then(createdProjects => console.log(`${createdProjects.length} projects created`))
    .catch(err => console.log(err))
    .finally(() => mongoose.connection.close())
})